### ISSUE TITLE
Single-expression ES6 arrow functions being treated as Promises

### ISSUE THREAD

**Issue by OOPMan** [unitjs/unit.js#10]
I originally filed this issue with MochaJS (https://github.com/mochajs/mocha/issues/1865) but the developer investigated and determined that the issue lies with Unit.JS. 

Original report:

I have some test code I am converting to ES6.

The ES5 version of the code is as follows:
```
it("should be a function", () => {
    test.function(encapsulate);
});
```

Converting it to ES6 Arrow functions one would think to use the following form:
```
it("should be a function", () => test.function(encapsulate));
```

Unfortunately, this test fails because Mocha seems to think that if a value is returned by a test it *must* be a Promise and works on the assumption that is is one. This breaks the above form.

Instead, one is forced to do the following:
```
it("should be a function", () => { test.function(encapsulate) });
```

While there isn't much difference I do think the 2nd form is optimally readable and it would be nice if Mocha allowed some way to handle it...

MochaJS developers final discovery:
Changing one of the specs to:
```
        it("should produce a function", () => {
            console.log(test.function(instantiator).then)
            test.function(instantiator)
        });
```
Reveals that unit.js returns an object with a then function. It seems to be an invalid promise implementation, as seen below:
```
test.function(instantiator).then(function(res) {
    console.log('res', res)
}, function(err) {
    console.log('err', err);
});

// Runs both resolve and reject callbacks
// res undefined
// err undefined
```
So that's either a bug with https://github.com/unitjs/unit.js or it's simply not meant to be used that way. Might wanna ping them! :)

**Comment by Nicolab** [comment]
Hello,

it's not a bug of Unit.js see in the guide [http://unitjs.com/guide/helpers.html#then-](http://unitjs.com/guide/helpers.html#then-) and in the [API doc](http://unitjs.com/api/helpers.html#then)

The method `then` is a BDD style (Given / When / Then). It does nothing, is just pass-through method for a fluent chain. If a function is passed, it is called.

If you want with a promise, look [http://unitjs.com/guide/promise.html](http://unitjs.com/guide/promise.html) (promisified: Given / When / Then)

**Comment by Nicolab** [comment]
Maybe it would be interesting to provide `test.functionAsync()`.

However, just to avoid putting the braces in a function arrow, I do not know if it is necessar to change a whole API of Unit.js.
If you want, you can promisify `test.function` to a custom `test.functionAsync`

**Comment by OOPMan** [comment]
Hrrrrrrrrmmmmm, is there no agreed on way to detect whether an object with a function named ```then``` is a Promise or not?

**Comment by Nicolab** [comment]
Yes :)

`test.promise.is(value)`
Returns `true` is `value` is a `Promise`, `false` if not a `Promise`

```js
if(test.promise.is(myFunction)) {
  console.log('Is a promise');
}
```

**Comment by OOPMan** [comment]
Right, but that doesn't really apply in this case...

**Comment by Nicolab** [comment]
Maybe I not understood what you want to do...

If you want checking that a function is a promise and return a promise for avoid to write the braces of an arrow function ?

Can be something like this (not tested but should be work): 

```js
// add in a bootstrap file or on top of you test file
test.functionAsync = (fn) => {
  test.function(fn).bool(test.promise.is(fn)).isTrue();
  return fn();
};
```

Then you can:
```js
it("should be a promise", () => test.functionAsync(encapsulate));
```

Another way for returning a promise to Mocha (without testing if the function is a promise):
```js
// add in a bootstrap file or on top of you test file
test.promisified = (fn) => {
  return new test.promise();
};
```

Then you can:
```js
it("should be a function", () => test.function(encapsulate).promisified());
```

You can create a custom asserter, passing what you want. Also if needed, you can use [dependency injection](http://unitjs.com/guide/dependency-injection.html) with the IoC container.

**Comment by OOPMan** [comment]
Hmmmmmmmm, I'll give that a go :-)
