### ISSUE TITLE
What are functions "it" and "describe" doing?

### ISSUE THREAD

**Issue by JanisE** [unitjs/unit.js#13]
Are there definitions of functions "it" and "describe" somewhere in the docs? I've clicked through the Spec and API doc sections, and I cannot find a description of neither of these.

As a noun, "it" leaves me especially baffled as to what it should be doing. Also, when I call "describe", what exactly is it supposed to be doing/describing?

Thanks!

**Comment by Nicolab** [comment]
Hello,

it's [Mocha](http://unitjs.com/guide/mocha.html) that provides these functions.
