### ISSUE TITLE
Provide Typescript definition files

### ISSUE THREAD

**Issue by mattbishop** [unitjs/unit.js#18]
I want to use unit.js in my Typescript tests but I can't find a typescript definition file to give me the interface declarations. It would be great to have the unit.js API defined for us TS folks.

https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

**Comment by Nicolab** [comment]
Unit.js is open, feel free to add.

**Comment by xenoterracide** [comment]
same issue
