### ISSUE TITLE
Don't call sinon spys when passed to helpers 

### ISSUE THREAD

**Issue by rnikoopour** [unitjs/unit.js#21]
Sinon spies are passed called when passed to helper functions such as given:

```
const test = {};
test
    .given(test.foo = sinon.spy())
    .then(() => console.log(test.foo.called)) //true
```

Is there anyway to prevent this behavior other than wrapping the `test.foo = sinon.spy()` in a function?

**Comment by Nicolab** [comment]
Yes : 

```js
[.if(test.foo = sinon.spy())](http://unitjs.com/api/helpers.html#if)
```
and: 

```js
[.and(test.foo = sinon.spy())](http://unitjs.com/api/helpers.html#and)
```

Attention in your example, `test` is unit.js (object) and an empty object (const test = {}).

**Comment by rnikoopour** [comment]
Ah sorry about that!  I really liked the given syntax and was trying to follow that.

Cheers!

**Comment by Nicolab** [comment]
Also, you can:

```js
test
    .given(() => foo = sinon.spy())
    .when(foo)
    .then(() => console.log(foo.called)) //true
```
or:
```js
test
    .given(() => foo = sinon.spy())
    .when(() => foo(anyArg))
    .then(() => console.log(foo.called)) //true
```
