### ISSUE TITLE
docs wrong for should.eql?

### ISSUE THREAD

**Issue by greggman** [unitjs/unit.js#25]
The docs here for `should.eql` say

     [1, 2, 3].should.eql({ '0': 1, '1': 2, '2': 3 });

But the should docs say 

     [ 'a' ].should.not.be.eql({ '0': 'a' });

**Comment by Nicolab** [comment]
It's not wrong. 
The `should.eql` doc has been modified. However, the old example is still valid (`[1, 2, 3].should.eql({ '0': 1, '1': 2, '2': 3 });`).

**Comment by Nicolab** [comment]
Now, the doc is up to date.
