### ISSUE TITLE
test.number.isNaN

### ISSUE THREAD

**Issue by joeax** [unitjs/unit.js#7]
Having isNaN()/isNotNaN() would be helpful for testing numbers. For example:
```
test.number(parseFloat("not a number")).isNaN()
test.number(5.3).isNotNaN()
```
Now, I could just use ```is(NaN)``` and that seems to work, but that leads to confusion as to whether or not this is using the global built in isNaN() under the hood, as it makes it appear as if NaN === itself when it shouldn't. See this article on StackOverflow: http://stackoverflow.com/questions/10034149/why-is-nan-not-equal-to-nan

**Comment by Nicolab** [comment]
Hello,

good idea :+1: 

I will add :)

**Comment by Nicolab** [comment]
Released in unit.js@1.2.0 :)

__Doc__
  * [test.number(actual).isNaN()](http://unitjs.com/api/number.html#isNaN)
  * [test.number(actual).isNotNaN()](http://unitjs.com/api/number.html#isNotNaN)

Of course are available with [test.value()](http://unitjs.com/api/value.html)

 * [test.value(parseInt('not a number', 10)).isNaN()](http://unitjs.com/api/value.html#isNaN)
 * [test.value(undefined).isNotNaN()](http://unitjs.com/api/value.html#isNotNaN)

That's done :white_check_mark:

**Comment by joeax** [comment]
This is awesome, thanks!
