### ISSUE TITLE
isLessThanOrEqualTo

### ISSUE THREAD

**Issue by jacksonrayhamilton** [unitjs/unit.js#8]
I would like it if there were `isLessThanOrEqualTo` and `isGreaterThanOrEqualTo` methods on the number helper. Can this be added?

**Comment by Nicolab** [comment]
Hello,

yes it can be added :)

while waiting there are several ways, example these two: 

chainable
```js
test.number(2015).isValid(function(it){
    return it >= 2015;
  });
```

also (not chainable)
```js
test.assert(value >= 2015);
```

It makes me think that `test.assert()` should be chainable.
