### ISSUE TITLE
unit package name

### ISSUE THREAD

**Issue by bucaran** [unitjs/unit.js#9]
I have name-"squatting" the `unit` package at npm for a while, but I am still undecided as to what I should use it for. I see you have a project going on that could benefit from this package name. If you are interested let me know and I will unpublish so that you folks can go ahead and take it.

Regards.

**Comment by Nicolab** [comment]
Hello,

Yes, nice :)
Thank you!

**Comment by bucaran** [comment]
Done, go ahead and get it while it's on the wild :P

**Comment by Nicolab** [comment]
It's ok, thanks :wink:
